resources:
  - url: http://127.0.0.1:5000/better-calendar-card.js
    type: module
views:
  - cards:
      - type: custom:better-calendar-card
        name: Better Calendar Card Development
        entity: sun.sun
        test_gui: true
